# server config
server:
 port: 8080

spring:
 # DB config
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://3.35.137.217:3306/readio
  username: readio
  password: readio

 # fileupload config
 servlet:
  multipart:
   enabled: true
   max-request-size: 10MB
   max-file-size: 1MB
 web:
  resources:
   static-locations: classpath:/img/

 # JPA config
 jpa:
  generate-ddl: false
  database: mysql
  properties:
   hibernate:
    format_sql: true
    highlight_sql: true
    use_sql_comments: true

 # 회원가입 시간대때문에 추가
 jackson:
  time-zone: Asia/Seoul

kakao:
 client-id: 4f6af9935c365a04789a592b6527b7ea
 redirect-uri: http://localhost:8080/oauth/kakao/callback
 client-secret: ZNDVceO6kZwR9aNATSmDDoWgSG6cWNDi

# static resource(image media file) config
## ???? ??? ??, ?? ? ??? ??? ???(@Value)?? ??
image:
 add-resource-locations: classpath:/static/img/
 add-resource-handler: /img/**
 image-dir: src/main/resources/static/img
 image-url: http://localhost:8080/img/


# security(jwt) config
jwt:
 secret: BWQ3NDiE+stVlnYfuLeHZ0i2hIRhoGZKIrHAnj0OPedv3aBEOPWJQ9KqqmH/XYWam6MeGG8+7gs2Rbs5ID0Vdg==
 expiration: 28800000 # 8시간, 밀리초 단위 / 3시간:10800000 / 24시간:86400000

# springdoc open-api config
springdoc:
 swagger-ui:
  path: /swagger-ui.html
# packages-to-scan: com.team.teamreadioserver.notion.controller

# logging config
logging:
 level:
  root: info
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  com.team.teamreadioserver.user.mapper: DEBUG   # UserMapper 로그 디버그 출력
  com.team.teamreadioserver.user.admin.mapper.AdminMapper: DEBUG   # AdminMapper 로그 디버그 출력
  java.sql: DEBUG
  org.mybatis: DEBUG                             # MyBatis 전체 로그 디버그 출력 (선택)

mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.team.teamreadioserver.user.dto

aladin:
 ttbkey: ttbehfvls09271435001

 # application.yml
 logging:
  level:
   org:
    springframework:
     web: DEBUG
     security: DEBUG
   com.team.teamreadioserver: DEBUG # 사용자 패키지

  spring:
   jpa:
    database-platform: org.hibernate.dialect.MySQLDialect # MySQL 8 버전 예시
    # properties:
    #  hibernate:
    #    dialect: org.hibernate.dialect.MySQL8Dialect

 mail:
  host: smtp.gmail.com
  port: 587
  username: qhrud647461@gmail.com
  password: ptwd gsvu lpvg vaow
  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true
      required: true
     connectiontimeout: 5000
     timeout: 5000
     writetimeout: 5000
  auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

