# server config
server:
 port: 8080

spring:
 # DB config
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://3.35.137.217:3306/readio
  username: readio
  password: readio

# fileupload config
 servlet:
  multipart:
   enabled: true
   max-request-size: 10MB
   max-file-size: 1MB
 web:
  resources:
   static-locations: classpath:/img/

# JPA config
 jpa:
  generate-ddl: false
  database: mysql
  properties:
   hibernate:
    format_sql: true
    highlight_sql: true
    use_sql_comments: true

# static resource(image media file) config
## ???? ??? ??, ?? ? ??? ??? ???(@Value)?? ??
image:
 add-resource-locations: classpath:/static/img/
 add-resource-handler: /img/**
 image-dir: src/main/resources/static/img
 image-url: http://localhost:8080/img


# security(jwt) config
jwt:
 secret: BWQ3NDiE+stVlnYfuLeHZ0i2hIRhoGZKIrHAnj0OPedv3aBEOPWJQ9KqqmH/XYWam6MeGG8+7gs2Rbs5ID0Vdg==


# springdoc open-api config
springdoc:
 swagger-ui:
  path: /swagger-ui.html

# logging config
logging:
 level:
  root: info
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.team.teamreadioserver.user.dto
